<td class="label"></td>
<td class="value">
    <button id="eu_countries_selector">Select only EU countries</button>
</td>
<td class="use-default"></td>
<script>
    require([
        'jquery'
    ], function ($) {
        $(function () {
            $('#eu_countries_selector').click(function(event) {
                event.preventDefault();

                $('#general_country_allow').val($('#general_country_eu_countries').val())
            })
        });
    });
</script>